title_name = "nx1"
title_id = "4156089E" #
hash = "76120D775C654F35" # 0-Nightly MP maps.mp.xex
#media_id = "00000000" 

[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x82502298
        value = 0x4E800020


[[patch]]
    name = "Ingame Console Fix"
    desc = "Ingame Console Fix for Xenia keyboard passthrough"
    author = "And799"
    is_enabled = true

    [[patch.be32]]
        address = 0x8257875C 
        value = 0x6000000
		
[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x827BD938
        value = 0x38A02000
