title_name = "nx1"
title_id = "4156089E" # 
hash = "3C876080C1FFB9AB" # 1-nx1sp.xex
#media_id = "00000000"

[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x824bcd10 # 
        value = 0x4E800020
		
		[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x8246A368 # 
        value = 0x4E800020
		
[[patch]]
    name = "Aspect ratio"
    author = "Clippy95"
    is_enabled = true

    [[patch.f32]]
        address = 0x8214053C
        value = 2.38888888889
		
[[patch]]
    name = "720p"
    desc = "Makes the game run at 720p instead of 600p. Currently disables AA until a solution's found."
    author = "Tervel"
    is_enabled = false

    [[patch.be16]]
        address = 0x82807626
        value = 0x0500
    [[patch.be16]]
        address = 0x8280762A
        value = 0x02D0
    [[patch.be8]]
        address = 0x8280763F
        value = 0x00
		
[[patch]]
    name = "black"
    desc = "Makes the game run at 720p instead of 600p. Currently disables AA until a solution's found."
    author = "Tervel"
    is_enabled = true

    [[patch.be32]]
        address = 0x82529CA0 # black
        value = 0x4E800020
		
		
	[[patch]]
    name = "stub MAssertVargs"
    author = "and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x824bcd10
        value = 0x4E800020

[[patch]]
    name = "Ingame Console Fix"
    desc = "Ingame Console Fix for Xenia keyboard passthrough"
    author = "And799"
    is_enabled = true

    [[patch.be32]]
        address = 0x8251E97C
        value = 0x6000000
		
[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x827BD938
        value = 0x38A02000

[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true
    [[patch.be32]]
        address = 0x82810EF0
        value = 0x38A02000

[[patch]]
    name = "Remove white flickering box"
    desc = "disables gp_rdvar_camo_enabled which caused flickering on the top left of the screen"
    author = "Clippy95, and799"
    is_enabled = true

    [[patch.be32]]
        address = 0x824D4734
        value = 0x38A02000